### ISSUE TITLE
Issue / PR template proposal

### ISSUE THREAD

**Issue by xXenvy** [sectasy0/zcached#29]
Currently all proposals / bugs have to be written from scratch. Templates for issues and pr's could help with adding them. [Reference.](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

We could even use that ready sample: https://github.com/stevemao/github-issue-templates/tree/master/simple

**Comment by sectasy0** [comment]
Resolved.
